/*
 * Flyefit API
 *
 * This is FLYEfit's API for access it's internal member database
 *
 * OpenAPI spec version: 0.4.0
 * Contact: api@flyefit.ie
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Gender :  IEquatable<Gender>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="Gender" /> class.
        /// </summary>
        /// <param name="GenderId">GenderId.</param>
        /// <param name="_Gender">_Gender.</param>
        public Gender(int? GenderId = default(int?), string _Gender = default(string))
        {
            this.GenderId = GenderId;
            this._Gender = _Gender;
            
        }

        /// <summary>
        /// Gets or Sets GenderId
        /// </summary>
        [DataMember(Name="genderId")]
        public int? GenderId { get; set; }
        /// <summary>
        /// Gets or Sets _Gender
        /// </summary>
        [DataMember(Name="gender")]
        public string _Gender { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Gender {\n");
            sb.Append("  GenderId: ").Append(GenderId).Append("\n");
            sb.Append("  _Gender: ").Append(_Gender).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((Gender)obj);
        }

        /// <summary>
        /// Returns true if Gender instances are equal
        /// </summary>
        /// <param name="other">Instance of Gender to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Gender other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.GenderId == other.GenderId ||
                    this.GenderId != null &&
                    this.GenderId.Equals(other.GenderId)
                ) && 
                (
                    this._Gender == other._Gender ||
                    this._Gender != null &&
                    this._Gender.Equals(other._Gender)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.GenderId != null)
                    hash = hash * 59 + this.GenderId.GetHashCode();
                    if (this._Gender != null)
                    hash = hash * 59 + this._Gender.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(Gender left, Gender right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Gender left, Gender right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
