/*
 * Flyefit API
 *
 * This is FLYEfit's API for access it's internal member database
 *
 * OpenAPI spec version: 0.4.0
 * Contact: api@flyefit.ie
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// A colleciton containing a list of gyms
    /// </summary>
    [DataContract]
    public partial class GymCollection :  IEquatable<GymCollection>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="GymCollection" /> class.
        /// </summary>
        /// <param name="Gyms">Gyms.</param>
        public GymCollection(List<Gym> Gyms = default(List<Gym>))
        {
            this.Gyms = Gyms;
            
        }

        /// <summary>
        /// Gets or Sets Gyms
        /// </summary>
        [DataMember(Name="gyms")]
        public List<Gym> Gyms { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GymCollection {\n");
            sb.Append("  Gyms: ").Append(Gyms).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((GymCollection)obj);
        }

        /// <summary>
        /// Returns true if GymCollection instances are equal
        /// </summary>
        /// <param name="other">Instance of GymCollection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GymCollection other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Gyms == other.Gyms ||
                    this.Gyms != null &&
                    this.Gyms.SequenceEqual(other.Gyms)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Gyms != null)
                    hash = hash * 59 + this.Gyms.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(GymCollection left, GymCollection right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GymCollection left, GymCollection right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
